spring.application.name=ems-backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ems}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:nguyen2701}
 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update