spring.application.name=ems-backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ems}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:nguyen2701}
 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=${JWT_SECRET:day-la-chuoi-bi-mat-tam-thoi-dung-de-hoc-nen-doi-lai-khi-deploy-that-nhe-ban}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}